# Synodal Bible & Mother

## Summary

In [1]:
# Code summary of below

In [2]:
!python --version

Python 3.11.4

## Import

### Libraries

In [3]:
from backend import *
num_cores = int(mp.cpu_count()-2)
print(f"Number of cores : {num_cores}")

Number of cores : 38

In [4]:
#%matplotlib inline

### Definitions

In [5]:
texts = '../texts/fiction/utf8/'

libCols = ['author','pub_year','title','text']
tokenOHCO = ['w_id','part_num','para_num', 'sent_num', 'token_num']
tokenCols = ['p_id', 'start', 'stop', 'text', 'token_id', 'head_id', 'rel', 'pos', 'lemma', 'anim', 'aspect', \
             'case', 'degree', 'gender', 'mood', 'number', 'person', 'tense', 'verb_form', 'voice']

In [6]:
motherTokenDf = pd.read_pickle('./proc/MotherTokendf.pkl')
bibleTokenDf = pd.read_pickle('./proc/BibleTokenDf.pkl')
confessionTokenDf = pd.read_pickle('./proc/ConfessionTokenDf.pkl')

In [7]:
good_pos = ['NOUN', 'ADJ', 'VERB', 'PROPN']

In [8]:
# add stopword boolean, True if all attribute columns are null
motherTokenDf = add_stopword(motherTokenDf)
bibleTokenDf = add_stopword(bibleTokenDf)
confessionTokenDf = add_stopword(confessionTokenDf)

## Bible and Mother Token Dataframes

In [9]:
bibleTokenDf

,p_id,start,stop,text,token_id,head_id,rel,pos,lemma,anim,...,case,degree,gender,mood,number,person,tense,verb_form,voice,stopword
id,,,,,,,,,,,,,,,,,,,,,
1,1,0,1,В,1_1,1_2,case,ADP,в,None,...,None,None,None,None,None,None,None,None,None,True
2,1,2,8,начале,1_2,1_3,obl,NOUN,начало,Inan,...,Loc,None,Neut,None,Sing,None,None,None,None,False
3,1,9,17,сотворил,1_3,1_0,root,VERB,сотворить,None,...,None,None,Masc,Ind,Sing,None,Past,Fin,Act,False
4,1,18,21,Бог,1_4,1_3,nsubj,PROPN,бог,Anim,...,Nom,None,Masc,None,Sing,None,None,None,None,False
5,1,22,26,небо,1_5,1_3,obj,NOUN,небо,Inan,...,Acc,None,Neut,None,Sing,None,None,None,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675064,37086,32,38,Христа,1_5,1_4,flat:name,PROPN,христос,Anim,...,Gen,None,Masc,None,Sing,None,None,None,None,False
675065,37086,39,41,со,1_6,1_8,case,ADP,с,None,...,None,None,None,None,None,None,None,None,None,True
675066,37086,42,47,всеми,1_7,1_8,det,DET,весь,None,...,Ins,None,None,None,Plur,None,None,None,None,True
675067,37086,48,52,вами,1_8,1_4,nmod,PRON,вы,None,...,Ins,None,None,None,Plur,2,None,None,None,True
675068,37086,54,59,Аминь,2_1,2_0,root,PROPN,аминь,Inan,...,Gen,None,Fem,None,Sing,None,None,None,None,False

In [10]:
bibleTokenDf.loc[bibleTokenDf.stopword == False]

,p_id,start,stop,text,token_id,head_id,rel,pos,lemma,anim,...,case,degree,gender,mood,number,person,tense,verb_form,voice,stopword
id,,,,,,,,,,,,,,,,,,,,,
2,1,2,8,начале,1_2,1_3,obl,NOUN,начало,Inan,...,Loc,None,Neut,None,Sing,None,None,None,None,False
3,1,9,17,сотворил,1_3,1_0,root,VERB,сотворить,None,...,None,None,Masc,Ind,Sing,None,Past,Fin,Act,False
4,1,18,21,Бог,1_4,1_3,nsubj,PROPN,бог,Anim,...,Nom,None,Masc,None,Sing,None,None,None,None,False
5,1,22,26,небо,1_5,1_3,obj,NOUN,небо,Inan,...,Acc,None,Neut,None,Sing,None,None,None,None,False
7,1,29,34,землю,1_7,1_5,conj,NOUN,земля,Inan,...,Acc,None,Fem,None,Sing,None,None,None,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
675060,37086,0,9,Благодать,1_1,1_2,nsubj,NOUN,благодать,Inan,...,Nom,None,Fem,None,Sing,None,None,None,None,False
675061,37086,10,17,Господа,1_2,1_1,appos,PROPN,господь,Anim,...,Gen,None,Masc,None,Sing,None,None,None,None,False
675063,37086,25,31,Иисуса,1_4,1_1,nmod,PROPN,иисус,Anim,...,Gen,None,Masc,None,Sing,None,None,None,None,False
675064,37086,32,38,Христа,1_5,1_4,flat:name,PROPN,христос,Anim,...,Gen,None,Masc,None,Sing,None,None,None,None,False
675068,37086,54,59,Аминь,2_1,2_0,root,PROPN,аминь,Inan,...,Gen,None,Fem,None,Sing,None,None,None,None,False

In [11]:
motherTokenDf#.set_index(['p_id','token_id'])

,p_id,start,stop,text,token_id,head_id,rel,pos,lemma,anim,...,case,degree,gender,mood,number,person,tense,verb_form,voice,stopword
id,,,,,,,,,,,,,,,,,,,,,
1,1,7,13,Каждый,1_1,1_2,det,DET,каждый,None,...,Acc,None,Masc,None,Sing,None,None,None,None,True
2,1,14,18,день,1_2,1_28,obl,NOUN,день,Inan,...,Acc,None,Masc,None,Sing,None,None,None,None,False
3,1,19,22,над,1_3,1_5,case,ADP,над,None,...,None,None,None,None,None,None,None,None,None,True
4,1,23,30,рабочей,1_4,1_5,amod,ADJ,рабочий,None,...,Ins,Pos,Fem,None,Sing,None,None,None,None,False
5,1,31,40,слободкой,1_5,1_28,obl,NOUN,слободка,Inan,...,Ins,None,Fem,None,Sing,None,None,None,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86005,4436,7,13,Кто-то,1_1,1_2,nsubj,PRON,кто-то,None,...,Nom,None,None,None,None,None,None,None,None,True
86006,4436,14,21,ответил,1_2,1_0,root,VERB,ответить,None,...,None,None,Masc,Ind,Sing,None,Past,Fin,Act,False
86007,4436,22,24,ей,1_3,1_2,iobj,PRON,она,None,...,Dat,None,Fem,None,Sing,3,None,None,None,True
86008,4436,25,32,громким,1_4,1_5,amod,ADJ,громкий,None,...,Dat,Pos,None,None,Plur,None,None,None,None,False
86009,4436,33,41,рыданием,1_5,1_2,obl,NOUN,рыдание,Anim,...,Dat,None,Masc,None,Plur,None,None,None,None,False

In [12]:
motherTokenDf.loc[motherTokenDf.stopword == False]

,p_id,start,stop,text,token_id,head_id,rel,pos,lemma,anim,...,case,degree,gender,mood,number,person,tense,verb_form,voice,stopword
id,,,,,,,,,,,,,,,,,,,,,
2,1,14,18,день,1_2,1_28,obl,NOUN,день,Inan,...,Acc,None,Masc,None,Sing,None,None,None,None,False
4,1,23,30,рабочей,1_4,1_5,amod,ADJ,рабочий,None,...,Ins,Pos,Fem,None,Sing,None,None,None,None,False
5,1,31,40,слободкой,1_5,1_28,obl,NOUN,слободка,Inan,...,Ins,None,Fem,None,Sing,None,None,None,None,False
7,1,44,50,дымном,1_8,1_34,conj,NOUN,дымный,Inan,...,Loc,None,Masc,None,Sing,None,None,None,None,False
8,1,52,60,масляном,1_10,1_11,amod,VERB,масляный,None,...,Loc,None,Masc,None,Sing,None,Pres,Part,Act,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86003,4434,54,61,хрипела,2_2,2_0,root,ADJ,хрипеть,None,...,None,Pos,Fem,None,Sing,None,None,None,None,False
86004,4435,10,20,Несчастные,1_2,1_0,root,ADJ,несчастный,None,...,Nom,Pos,None,None,Plur,None,None,None,None,False
86006,4436,14,21,ответил,1_2,1_0,root,VERB,ответить,None,...,None,None,Masc,Ind,Sing,None,Past,Fin,Act,False
86008,4436,25,32,громким,1_4,1_5,amod,ADJ,громкий,None,...,Dat,Pos,None,None,Plur,None,None,None,None,False
86009,4436,33,41,рыданием,1_5,1_2,obl,NOUN,рыдание,Anim,...,Dat,None,Masc,None,Plur,None,None,None,None,False

In [13]:
confessionTokenDf

,p_id,start,stop,text,token_id,head_id,rel,pos,lemma,anim,...,case,degree,gender,mood,number,person,tense,verb_form,voice,stopword
id,,,,,,,,,,,,,,,,,,,,,
1,1,10,19,Позвольте,1_2,1_0,root,VERB,позволить,None,...,None,None,None,Imp,Plur,2,None,Fin,Act,False
2,1,20,30,рассказать,1_3,1_2,xcomp,VERB,рассказать,None,...,None,None,None,None,None,None,None,Inf,Act,False
3,1,31,36,жизнь,1_4,1_3,obj,NOUN,жизнь,Inan,...,Acc,None,Fem,None,Sing,None,None,None,None,False
4,1,37,40,мою,1_5,1_17,det,DET,мой,None,...,Acc,None,Fem,None,Sing,None,None,None,None,True
5,1,42,49,времени,1_7,1_10,obj,NOUN,время,Inan,...,Gen,None,Neut,None,Sing,None,None,None,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47480,2360,283,291,великого,1_49,1_50,amod,ADJ,великий,None,...,Gen,Pos,Neut,None,Sing,None,None,None,None,False
47481,2360,292,296,дела,1_50,1_11,obl,NOUN,дело,Inan,...,Gen,None,Neut,None,Sing,None,None,None,None,False
47482,2360,300,310,всемирного,1_52,1_53,amod,ADJ,всемирный,None,...,Gen,Pos,Masc,None,Sing,None,None,None,None,False
47483,2360,311,328,богостроительства,1_53,1_50,appos,NOUN,богостроительство,Inan,...,Gen,None,Neut,None,Sing,None,None,None,None,False
47484,2360,329,333,ради,1_54,1_11,advmod,NOUN,ради,Inan,...,Gen,None,Masc,None,Sing,None,None,None,None,False

In [14]:
lemmaDf = bibleTokenDf[['lemma']].loc[bibleTokenDf.stopword == False].join(motherTokenDf[['lemma']].loc[motherTokenDf.stopword == False], on='id', lsuffix='_bible', rsuffix='_mother')
lemmaDf

       lemma_bible lemma_mother
id
2           начало         день
3        сотворить          NaN
4              бог      рабочий
5             небо     слободка
7            земля       дымный
...            ...          ...
675060   благодать          NaN
675061     господь          NaN
675063       иисус          NaN
675064     христос          NaN
675068       аминь          NaN

[345090 rows x 2 columns]

## Shared Lemmas

In [15]:
bible_lemmas = bibleTokenDf.loc[bibleTokenDf.stopword == False].lemma
mother_lemmas = motherTokenDf.loc[motherTokenDf.stopword == False].lemma
confession_lemmas = confessionTokenDf.loc[confessionTokenDf.stopword == False].lemma

In [16]:
%%time
common_lemmas(bible_lemmas, mother_lemmas)

CPU times: user 3min 13s, sys: 157 ms, total: 3min 13s
Wall time: 3min 14s

"Shared unique words between text and the Bible: 3534, that's ~17.81%"

In [17]:
%%time
common_lemmas(bible_lemmas, confession_lemmas)

CPU times: user 2min 39s, sys: 46.8 ms, total: 2min 39s
Wall time: 2min 40s

"Shared unique words between text and the Bible: 3227, that's ~16.27%"

In [20]:
len(set(confession_lemmas))/47484

0.1261266953078932

In [21]:
bible_vc = bible_lemmas.to_frame().value_counts().to_frame()
mother_vc = mother_lemmas.to_frame().value_counts().to_frame()
confession_vc = confession_lemmas.to_frame().value_counts().to_frame()

In [22]:
bible_vc.reset_index().loc[bible_vc.reset_index().lemma == 'мать']

    lemma  count
137  мать    366

In [23]:
mother_vc.reset_index().loc[mother_vc.reset_index().lemma == 'отец']

    lemma  count
229  отец     34

In [24]:
confession_vc.reset_index().loc[confession_vc.reset_index().lemma == 'город']

     lemma  count
184  город     21

In [25]:
countDf = mother_vc.join(bible_vc, lsuffix='_mother', rsuffix='_bible')
countDf = countDf.join(confession_vc, lsuffix='_mother', rsuffix='_confession')
countDf = countDf.rename({'count':'count_confession'}, axis=1)

In [26]:
motherLemmaDf = countDf[:25].fillna(0).astype(int, errors='ignore')[['count_mother', 'count_bible']].style.background_gradient(cmap='plasma')
confessionLemmaDf = countDf.sort_values('count_confession', ascending=False)[:25].fillna(0).astype(int, errors='ignore')[['count_confession', 'count_bible']].style.background_gradient(cmap='plasma')
bibleLemmaDf = countDf.sort_values('count_bible', ascending=False)[:25].fillna(0).astype(int, errors='ignore').style.background_gradient(cmap='plasma')

In [27]:
display_side_by_side(motherLemmaDf, bibleLemmaDf, confessionLemmaDf)

def compare_list_frequency(*args,
                           consider_order=False,
                           consider_duplicates=True,
                           handle_unhashable=False,
                           key=None,
                           frequency_format="dict"):    
    list_hit_list = []
    for arg in args:
        list_hit_dict = {}
        other_args = args[:args.index(arg)] + args[args.index(arg)+1:]
        for word in set(arg):
            word_hit_count = 0
            for other_arg in other_args:
                word_hit_count += list(other_arg).count(word)
            if word_hit_count > 0:
                list_hit_dict[word] = word_hit_count
            #print(f"{word}: {list(bible_lemmas[:1000]).count(word)}")
        list_hit_list.append(list_hit_dict)

    return(list_hit_list)

In [29]:
comparison_lists = compare_list_frequency(list(mother_lemmas), list(bible_lemmas), list(confession_lemmas))

In [30]:
mother_lemmas.value_counts().to_frame()

             count
lemma
мать           983
сказать        697
человек        680
говорить       569
рука           478
...            ...
нагнать          1
отравить         1
оголить          1
возбуждаясь      1
десятина         1

[7259 rows x 1 columns]

In [31]:
compDf = pd.DataFrame(comparison_lists).transpose(copy=True).fillna(0).astype(int)
compDf.columns = ['mother', 'bible', 'confession']
compDf = compDf.fillna(0).astype(int, errors='ignore')
compDf.sample(25).style.background_gradient(cmap='plasma')

In [32]:
mcompDf = compDf.sort_values('mother', axis=0, ascending=False)[:25].style.background_gradient(cmap='plasma')
bcompDf = compDf.sort_values('bible', axis=0, ascending=False)[:25].style.background_gradient(cmap='plasma')
ccompDf = compDf.sort_values('confession', axis=0, ascending=False)[:25].style.background_gradient(cmap='plasma')

In [33]:
display_side_by_side(mcompDf, bcompDf, ccompDf)

In [34]:
def ListSplit(lst, numGroups, sort=True): 
    """Takes a list and a number and splits the 
    list into evenly divided n groups (as much as possible)"""
    # choose to sort list by ascending
    if sort: 
        lst.sort()
    # get length of list given to sort
    listLen = len(lst)
    # groupLen is the maximum number of items per group to allow for the most groups <= numGroups in a list (numGroups-1 OR numGroups)
    groupLen = (listLen//numGroups) + (listLen % numGroups > 0)
    # yield generator object of nested listed with length of numGroups 
    for i in range(0,len(lst), groupLen): 
        yield lst[i:i+groupLen]

def token_window(lemma_array, window_size):
    token_window_array = np.array([])
    token_window_array = np.array([np.array(lemma_array[i:i+window_size]) for i in range(len(lemma_array)-(window_size-1))])
    return token_window_array

def token_window_mp(lemma_array, window_size):
    #token_window_array = np.array([])
    token_window_array = enumerate([list(lemma_array[i:i+window_size]) for i in range(len(lemma_array)-(window_size-1))])
    return token_window_array

def get_sim_count(child_window_array, parent_window_array, order_matters=False):
    work_sim_count = 0
    work_sim = []
    for child_window in child_window_array:
        child_sim = {}
        #print(f"child window: {child_window}")
        child_window_sim_total_count = 0
        for parent_window in parent_window_array:
            #print(f"parent window: {parent_window}")
            child_window_sim_sub_count = 0
            for i in range(len(child_window)):
                if order_matters:
                    if child_window[1][i] == parent_window[1][i]:
                        child_window_sim_total_count+=1
                        child_window_sim_sub_count+=1
                else:
                    if child_window[1][i] in parent_window[1]:
                        #print(f"{child_window[i]} is in parent!")
                        child_window_sim_total_count+=1
                        child_window_sim_sub_count+=1
                    #else:
                        #print(f"{child_window[i]} is not in parent!")
            child_sim.update({parent_window[0]: child_window_sim_sub_count})
        #print(f"{child_window}: {child_window_sim_total_count}")
        work_sim.append({child_window_sim_total_count: child_sim})
    return work_sim

def dna_test_windows(child_lemmas, parent_lemmas, window_size=10):
    sim_counter = 0
    #sim_list = np.array([])
    parent_window_array = token_window(parent_lemmas, window_size)
    child_window_array = token_window(child_lemmas, window_size)
    sim_list = get_sim_count(child_window_array, parent_window_array)
    #print(sim_list)
    return sim_list

def dna_test_windows_mp(child_lemmas, parent_lemmas, window_size=10):
    #child_lemmas, parent_lemmas = cnp_lemmas[0], cnp_lemmas[1]
    #print(f"Child lemmas: {child_lemmas}")
    #print(f"Parent lemmas: {parent_lemmas[:10]}")
    sim_counter = 0
    sim_list = np.array([])
    parent_window_array = token_window_mp(parent_lemmas, window_size)
    child_window_array = token_window_mp(child_lemmas, window_size)
    sim_list = get_sim_count(child_window_array, parent_window_array)
    return sim_list

def window_count_sim_mp(child_window_array, parent_window_array, order_matters=False):
    sim_count_tuples = {}
    for (c_sub_array_id, c_sub_array_list) in child_window_array:
        c_sub_sim_count = 0
        for (p_sub_array_id, p_sub_array_list) in parent_window_array:
            c_p_sim_count = 0
            for i in range(len(c_sub_array_list)):
                if order_matters:
                    if c_sub_array_list[i] == p_sub_array_list[i]:
                        c_sub_sim_count += 1
                        c_p_sim_count += 1
                else:
                    if c_sub_array_list[i] in p_sub_array_list:
                        c_sub_sim_count += 1
                        c_p_sim_count += 1
            sim_count_tuples[(c_sub_array_id, p_sub_array_id)] = c_p_sim_count
    return sim_count_tuples

def list_split(lst, numGroups, sort=True): 
    """Takes a list and a number and splits the 
    list into evenly divided n groups (as much as possible)"""
    # choose to sort list by ascending
    if sort: 
        lst.sort()
    # get length of list given to sort
    listLen = len(lst)
    # groupLen is the maximum number of items per group to allow for the most groups <= numGroups in a list (numGroups-1 OR numGroups)
    groupLen = (listLen//numGroups) + (listLen % numGroups > 0)
    # yield generator object of nested listed with length of numGroups 
    for i in range(0,len(lst), groupLen): 
        yield lst[i:i+groupLen]

def token_window_mp(lemma_array, window_size):
    #token_window_array = np.array([])
    token_window_array = enumerate([list(lemma_array[i:i+window_size]) for i in range(len(lemma_array)-(window_size-1))])
    return token_window_array

def window_count_sim_mp(child_window_array, parent_window_array, order_matters=False):
    sim_count_tuples = {}
    for (c_sub_array_id, c_sub_array_list) in child_window_array:
        c_sub_sim_count = 0
        for (p_sub_array_id, p_sub_array_list) in parent_window_array:
            c_p_sim_count = 0
            for i in range(len(c_sub_array_list)):
                if order_matters:
                    if c_sub_array_list[i] == p_sub_array_list[i]:
                        c_sub_sim_count += 1
                        c_p_sim_count += 1
                else:
                    if c_sub_array_list[i] in p_sub_array_list:
                        c_sub_sim_count += 1
                        c_p_sim_count += 1
            if order_matters: 
                if c_p_sim_count > 1: 
                    sim_count_tuples[(c_sub_array_id, p_sub_array_id)] = c_p_sim_count
            elif c_p_sim_count > 2: 
                sim_count_tuples[(c_sub_array_id, p_sub_array_id)] = c_p_sim_count
    return sim_count_tuples

def dna_test_windows_mp(child_lemmas, parent_lemmas, window_size=10):
    sim_list = {}
    parent_window_array = token_window_mp(parent_lemmas, window_size)
    child_window_array = token_window_mp(child_lemmas, window_size)
    sim_list = window_count_sim_mp(child_window_array, parent_window_array)
    return sim_list

In [35]:
child_window_array = list(token_window_mp(mother_lemmas, 7))
parent_window_array = list(token_window_mp(bible_lemmas, 7))

In [36]:
len(child_window_array)

46830

In [37]:
len(parent_window_array)

345084

In [38]:
%%time
if __name__ == "__main__":
    pool = Pool(processes=num_cores)
    #workerAssignments = ((x, bible_lemmas) for x in ListSplit(mother_lemmas[:198], num_cores, False))
    starmap_list = list(zip(list_split(child_window_array, num_cores), list_split(parent_window_array, num_cores)))
    print(f"Splitting into {num_cores} groups")
    start_time = time.time()
    sim_tuples = pool.starmap(window_count_sim_mp, starmap_list, chunksize=2)
    print(f"Finished in {round(time.time()-start_time, 3)} seconds.")
    pool.close()
    pool.join()
    #print(sim_tuples)

NameError: name 'list_split' is not defined

In [39]:
for i in range(len(sim_tuples)):
    print(f"len({i}): {len(sim_tuples[i])}")

NameError: name 'sim_tuples' is not defined

In [ ]:
total_sim_tuples = {}
for t in sim_tuples:
    total_sim_tuples.update(t)

In [ ]:
len(total_sim_tuples)

In [ ]:
sorted_sim_tuples = sorted(total_sim_tuples.items(), key=lambda x:x[1], reverse=True)
sorted_sim_tuples

In [ ]:
motherTokenDf.loc[motherTokenDf.p_id == 693]

In [ ]:
bibleTokenDf.loc[(bibleTokenDf.p_id == 5374) | (bibleTokenDf.p_id == 5373)]

In [ ]:
motherTokenDf.loc[motherTokenDf.lemma == "заботиться"]

In [ ]:
bibleTokenDf.loc[bibleTokenDf.lemma == "поступь"]

In [ ]:
child_window_array[7025:7030]

In [ ]:
parent_window_array[52840:52850]

In [ ]:
pd.DataFrame(child_window_array[7028][1])

In [ ]:
pd.DataFrame.from_dict({x:y for x,y in parent_window_array[:5]})

In [ ]:
sorted_consec_sim_tuples = sorted(total_consec_sim_tuples.items(), key=lambda x:x[1], reverse=True)

In [ ]:
sorted_consec_sim_tuples

In [ ]:
compareDf = pd.DataFrame()
for x,y in sim_tuples[9:16]:
    #print(child_window_array[x[0]][0])
    #print(child_window_array[x[0]][1])
    compareDf[child_window_array[x[0]][0]] = child_window_array[x[0]][1]
    compareDf[parent_window_array[x[1]][0]] = parent_window_array[x[1]][1]
    #compareDf[x[1]] = parent_window_array[x][1]

compareDf

In [ ]:
with open('./proc/sim_tuples.pkl', 'wb') as file:
    pickle.dump(sorted_sim_tuples, file)

In [ ]:
with open('./proc/consec_sim_tuples.pkl', 'wb') as file:
    pickle.dump(sorted_consec_sim_tuples, file)

In [ ]:
with open('./proc/sim_tuples.pkl', 'rb') as file:
    # The protocol version used is detected automatically, so we do not have to specify it.
    sim_tuples = pickle.load(file)

In [ ]:
with open('./proc/consec_sim_tuples.pkl', 'rb') as file:
    # The protocol version used is detected automatically, so we do not have to specify it.
    csim_tuples = pickle.load(file)

In [ ]:
csim_tuples

In [ ]:
sim_tuples

In [ ]:
pd.DataFrame(sim_tuples)

How do Gor'kii's *Mother* and the Synodal Bible overlap? 
windows of 3-5 words with 1-2+ of overlap